// CHECKPOINT UI translations recovered from the current offline translation run.
// Full generated dictionaries/state maps will replace/extend these progressively.
export const GENERATED_READY_LOCALES = ["bn","gu","hi","mr","pa","ta","te"];
export const GENERATED_DICTIONARIES = {
  mr:{"nav_find":"शोधा","nav_browse":"ब्राउझ करा","nav_map":"नकाशा","nav_whatif":"काय-जर","nav_constellation":"नक्षत्र","nav_saved":"जतन केले","browse_title":"प्रदेशानुसार ब्राउझ करा","browse_search_placeholder":"योजनेचे नाव किंवा वर्णन शोधा...","browse_search_button":"शोधा","browse_all":"सर्व","browse_central":"मध्यवर्ती","browse_state":"राज्य","card_benefit":"फायदाः","card_view_details":"तपशील पहा","scheme_about":"याबद्दल","scheme_benefits":"फायदे","scheme_eligibility_criteria":"पात्रतेचे निकष","scheme_how_to_apply":"अर्ज कसा करावा?","scheme_documents_required":"आवश्यक कागदपत्रे","scheme_apply_now":"आता अर्ज करा","scheme_official_page":"अधिकृत पान","saved_title":"जतन केलेल्या योजना","map_title":"राज्यानुसार योजनांचा शोध घ्या","lang_switch_label":"भाषा"},
  bn:{"nav_find":"খুঁজে বের করুন।","nav_browse":"ব্রাউজ করুন","nav_map":"মানচিত্র","nav_whatif":"কি-যদি","nav_constellation":"নক্ষত্রপুঞ্জ","nav_saved":"সংরক্ষিত","browse_title":"অঞ্চল অনুযায়ী ব্রাউজ করুন","browse_search_placeholder":"পরিকল্পনার নাম বা বিবরণ অনুসন্ধান করুন...","browse_search_button":"খোঁজখবর নিন।","browse_all":"সব","browse_central":"কেন্দ্রীয়","browse_state":"রাজ্য","card_benefit":"উপকারিতাঃ","card_view_details":"বিস্তারিত দেখুন","scheme_about":"সম্পর্কে","scheme_benefits":"উপকারিতা","scheme_eligibility_criteria":"যোগ্যতার মানদণ্ড","scheme_how_to_apply":"কিভাবে আবেদন করবেন","scheme_documents_required":"প্রয়োজনীয় নথি","scheme_apply_now":"এখনই আবেদন করুন","scheme_official_page":"অফিসিয়াল পেজ","saved_title":"সংরক্ষিত প্রকল্প","map_title":"রাজ্য অনুযায়ী প্রকল্পগুলি অন্বেষণ করুন","lang_switch_label":"ভাষা"},
  gu:{"nav_find":"શોધો","nav_browse":"બ્રાઉઝ કરો","nav_map":"નકશો","nav_whatif":"શું-જો","nav_constellation":"નક્ષત્ર","nav_saved":"સાચવવામાં આવી","browse_title":"પ્રદેશ પ્રમાણે બ્રાઉઝ કરો","browse_search_placeholder":"યોજનાનું નામ અથવા વર્ણન શોધો...","browse_search_button":"શોધો","browse_all":"બધા","browse_central":"કેન્દ્રીય","browse_state":"રાજ્ય","card_benefit":"લાભોઃ","card_view_details":"વિગતો જુઓ","scheme_about":"વિશે","scheme_benefits":"ફાયદાઓ","scheme_eligibility_criteria":"લાયકાત માપદંડ","scheme_how_to_apply":"કેવી રીતે અરજી કરવી","scheme_documents_required":"જરૂરી દસ્તાવેજો","scheme_apply_now":"હમણાં અરજી કરો","scheme_official_page":"સત્તાવાર પાનું","saved_title":"સાચવેલ યોજનાઓ","map_title":"રાજ્ય દ્વારા યોજનાઓનું અન્વેષણ કરો","lang_switch_label":"ભાષા"},
  pa:{"nav_find":"ਲੱਭੋ","nav_browse":"ਬ੍ਰਾਉਜ਼ ਕਰੋ","nav_map":"ਨਕਸ਼ਾ","nav_whatif":"ਕੀ-ਜੇ","nav_constellation":"ਤਾਰਾਮੰਡਲ","nav_saved":"ਸੰਭਾਲਿਆ ਗਿਆ","browse_title":"ਖੇਤਰ ਅਨੁਸਾਰ ਬ੍ਰਾਉਜ਼ ਕਰੋ","browse_search_placeholder":"ਸਕੀਮ ਦਾ ਨਾਮ ਜਾਂ ਵੇਰਵਾ ਲੱਭੋ...","browse_search_button":"ਖੋਜ ਕਰੋ","browse_all":"ਸਭ ਕੁੱਝ","browse_central":"ਕੇਂਦਰੀ","browse_state":"ਰਾਜ","card_benefit":"ਲਾਭ -","card_view_details":"ਵੇਰਵਾ ਵੇਖੋ","scheme_about":"ਬਾਰੇ","scheme_benefits":"ਲਾਭ","scheme_eligibility_criteria":"ਯੋਗਤਾ ਮਾਪਦੰਡ","scheme_how_to_apply":"ਕਿਵੇਂ ਕਰੀਏ ਅਪਲਾਈ","scheme_documents_required":"ਲੋਡ਼ੀਂਦੇ ਦਸਤਾਵੇਜ਼","scheme_apply_now":"ਹੁਣ ਅਰਜ਼ੀ ਦਿਓ","scheme_official_page":"ਅਧਿਕਾਰਤ ਸਫ਼ਾ","saved_title":"ਸੰਭਾਲੀਆਂ ਯੋਜਨਾਵਾਂ","map_title":"ਰਾਜ ਅਨੁਸਾਰ ਯੋਜਨਾਵਾਂ ਦੀ ਪਡ਼ਚੋਲ ਕਰੋ","lang_switch_label":"ਭਾਸ਼ਾ"},
  kn:{"nav_find":"ಹುಡುಕಿ","nav_browse":"ಬ್ರೌಸ್ ಮಾಡಿ","nav_map":"ನಕ್ಷೆ","nav_whatif":"ಏನು-ಇದ್ದರೆ","nav_constellation":"ನಕ್ಷತ್ರಪುಂಜ","nav_saved":"ಉಳಿಸಲಾಗಿದೆ.","browse_title":"ಪ್ರದೇಶದಿಂದ ಪ್ರದೇಶಕ್ಕೆ ಬ್ರೌಸ್ ಮಾಡಿ","browse_search_placeholder":"ಯೋಜನೆಯ ಹೆಸರು ಅಥವಾ ವಿವರಣೆಯನ್ನು ಹುಡುಕಿ...","browse_search_button":"ಹುಡುಕಿ","browse_all":"ಎಲ್ಲಾ","browse_central":"ಕೇಂದ್ರ","browse_state":"ರಾಜ್ಯ","card_benefit":"ಪ್ರಯೋಜನಃ","card_view_details":"ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ","scheme_about":"ಬಗ್ಗೆ","scheme_benefits":"ಪ್ರಯೋಜನಗಳು","scheme_eligibility_criteria":"ಅರ್ಹತಾ ಮಾನದಂಡಗಳು","scheme_how_to_apply":"ಅರ್ಜಿ ಸಲ್ಲಿಸುವುದು ಹೇಗೆ?","scheme_documents_required":"ಅಗತ್ಯ ದಾಖಲೆಗಳು","scheme_apply_now":"ಈಗಲೇ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ","scheme_official_page":"ಅಧಿಕೃತ ಪುಟ","saved_title":"ಉಳಿಸಿದ ಯೋಜನೆಗಳು","map_title":"ರಾಜ್ಯವಾರು ಯೋಜನೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ","lang_switch_label":"ಭಾಷೆ"},
  ml:{"nav_find":"കണ്ടെത്തുക","nav_browse":"ബ്രൌസ് ചെയ്യുക","nav_map":"ഭൂപടം","nav_whatif":"എന്താ -","nav_constellation":"നക്ഷത്രസമൂഹം","nav_saved":"സൂക്ഷിച്ചിരിക്കുന്നു.","browse_title":"പ്രദേശം അനുസരിച്ച് ബ്രൌസ് ചെയ്യുക","browse_search_placeholder":"സ്കീമിൻ്റെ പേരോ വിവരണമോ തിരയുക...","browse_search_button":"തിരയുക","browse_all":"എല്ലാം","browse_central":"കേന്ദ്ര","browse_state":"സംസ്ഥാനം","card_benefit":"ഗുണംഃ","card_view_details":"വിശദാംശങ്ങൾ കാണുക","scheme_about":"അതിനെക്കുറിച്ച്","scheme_benefits":"ആനുകൂല്യങ്ങൾ","scheme_eligibility_criteria":"യോഗ്യതാ മാനദണ്ഡങ്ങൾ","scheme_how_to_apply":"എങ്ങനെ അപേക്ഷിക്കാം","scheme_documents_required":"ആവശ്യമായ രേഖകൾ","scheme_apply_now":"ഇപ്പോൾ അപേക്ഷിക്കുക","scheme_official_page":"ഔദ്യോഗിക പേജ്","saved_title":"സംരക്ഷിച്ച പദ്ധതികൾ","map_title":"സംസ്ഥാനങ്ങൾക്കനുസരിച്ച് പദ്ധതികൾ പര്യവേക്ഷണം ചെയ്യുക","lang_switch_label":"ഭാഷ"}
};
export const GENERATED_STATE_NAMES = {};
