// AUTO-GENERATED by scripts/translate-catalog.py.
//
// This file is intentionally committed. The translation job runs offline (e.g. a
// free Colab GPU) and writes static artifacts; Vercel never runs a translation model.
//
// Until a locale has both a UI dictionary and a scheme-content pack, it is not
// activated in the language switcher.
export const GENERATED_READY_LOCALES = [];
export const GENERATED_DICTIONARIES = {};
export const GENERATED_STATE_NAMES = {};
